cleanup:
  auto_cleanup: true
  cleanup_items:
  - test_vector_databases
  - test_log_files
  - temporary_test_files
  preserve_items:
  - test_reports
  - test_database_backups
error_scenario_tests:
  data_validation_errors:
    enabled: true
    test_scenarios:
    - empty_data
    - malicious_data
    - encoding_errors
    - oversized_data
  database_errors:
    enabled: true
    test_scenarios:
    - file_not_found
    - permission_denied
    - schema_mismatch
    - connection_timeout
  llm_api_errors:
    enabled: true
    test_scenarios:
    - invalid_api_key
    - network_timeout
    - rate_limit_exceeded
    - invalid_response_format
  resource_exhaustion_tests:
    enabled: true
    test_scenarios:
    - memory_exhaustion
    - file_handle_exhaustion
    - cpu_overload
  vector_db_errors:
    enabled: true
    test_scenarios:
    - directory_permission_error
    - disk_space_insufficient
    - search_failure
    - embedding_model_error
functional_tests:
  database_operations:
    enabled: true
    max_test_records: 50
    test_batch_sizes:
    - 1
    - 5
    - 10
    - 20
  job_processing:
    enabled: true
    test_fallback_mode: true
    test_llm_mode: false
  resume_optimization:
    enabled: true
    test_optimization_types:
    - gap_analysis
    - skill_suggestions
    - content_optimization
    test_resume_formats:
    - basic
    - detailed
  system_initialization:
    enabled: true
    retry_count: 3
    timeout_seconds: 60
  vector_operations:
    enabled: true
    search_k_values:
    - 1
    - 3
    - 5
    - 10
    search_queries:
    - Python开发
    - Java工程师
    - 前端开发
    - 数据分析
    test_document_types:
    - overview
    - responsibility
    - requirement
    - skills
login:
  check_interval: 2
  failure_indicators:
  - .error-msg
  - .login-failed
  - .captcha-error
  - .password-error
  - .alert-danger
  login_url: https://login.51job.com/
  session_timeout: 7200
  success_indicators:
  - .user-info
  - .user-name
  - '[data-user]'
  - .logout
  - .member-center
  - .welcome-user
  wait_timeout: 300
login_mode:
  auto_save_session: true
  detail_page_delay: 3.0
  enabled: true
  login_retry_delay: 10
  max_login_attempts: 3
  require_login_for_details: true
  session_validation_interval: 300
  website: qiancheng
mode:
  close_on_complete: true
  debug: false
  development: false
  login_mode_enabled: true
  session_file: data/qiancheng_session.json
  skip_login: false
  use_saved_session: true
performance_tests:
  batch_processing_benchmark:
    acceptable_jobs_per_second: 2
    batch_sizes:
    - 1
    - 5
    - 10
    - 20
    - 50
    enabled: true
    max_jobs_per_batch: 100
  concurrent_processing_benchmark:
    acceptable_concurrent_speedup: 1.5
    concurrency_levels:
    - 1
    - 2
    - 4
    - 8
    enabled: true
    jobs_per_level: 20
  initialization_benchmark:
    acceptable_init_time_seconds: 10
    acceptable_memory_increase_mb: 100
    enabled: true
    test_runs: 5
  memory_usage_benchmark:
    acceptable_memory_per_job_mb: 5
    enabled: true
    job_checkpoints:
    - 10
    - 20
    - 50
    - 100
  vector_search_benchmark:
    acceptable_search_time_ms: 500
    enabled: true
    k_values:
    - 1
    - 3
    - 5
    - 10
    - 20
    search_queries: 10
rag_system:
  database:
    batch_size: 50
    path: ./data/jobs.db
  documents:
    create_comprehensive_doc: false
    types:
    - overview
    - responsibility
    - requirement
    - skills
    - basic_requirements
  llm:
    api_key: 0175134f27a040709d7541e14b4db353.V3KP9u8rZ0oQj9s9
    max_tokens: 1500
    model: glm-4-flash
    provider: zhipu
    retry_attempts: 3
    temperature: 0.1
    timeout_seconds: 30
  processing:
    batch_size: 50
    force_reprocess: false
    max_retry_attempts: 3
    skip_processed: true
  vector_db:
    collection_name: job_positions
    embeddings:
      device: cpu
      model_name: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
      normalize_embeddings: true
    persist_directory: ./data/test_chroma_db
test_data:
  sample_jobs:
  - company: 科技公司A
    description: 负责Python后端开发，熟悉Django/Flask框架，有数据库设计经验
    education: 本科及以上
    experience: 3-5年
    job_id: 1
    location: 北京
    salary: 20-30K
    title: Python后端开发工程师
  - company: 互联网公司B
    description: 负责Java微服务开发，熟悉Spring Boot，有分布式系统经验
    education: 本科及以上
    experience: 5-8年
    job_id: 2
    location: 上海
    salary: 30-50K
    title: Java高级开发工程师
  - company: 创业公司C
    description: 负责React/Vue前端开发，熟悉现代前端工程化工具
    education: 专科及以上
    experience: 2-4年
    job_id: 3
    location: 深圳
    salary: 15-25K
    title: 前端开发工程师
  sample_resumes:
  - current_position: Python开发工程师
    education: 本科 - 计算机科学
    name: 张三
    skills:
    - Python
    - Django
    - MySQL
    - Redis
    - Docker
    summary: 3年Python开发经验，熟悉Web开发和数据库设计
    years_of_experience: 3
  - current_position: Java开发工程师
    education: 硕士 - 软件工程
    name: 李四
    skills:
    - Java
    - Spring Boot
    - MySQL
    - Redis
    - Kafka
    summary: 5年Java开发经验，有微服务架构和分布式系统经验
    years_of_experience: 5
test_environment:
  database:
    backup_db_path: ./test_data/test_jobs_backup.db
    create_test_data: true
    test_db_path: ./data/jobs.db
    test_records_count: 10
  vector_db:
    cleanup_after_test: true
    collection_prefix: test_
    test_persist_directory: ./data/test_chroma_db
test_reporting:
  detail_level: full
  formats:
  - json
  - html
  include_performance_charts: true
  notifications:
    email_recipients: []
    enabled: false
    webhook_url: ''
  output_directory: ./test_reports
