backup:
  auto_backup: true
  backup_interval: daily
  retention:
    daily_backups: 7
    monthly_backups: 12
    weekly_backups: 4
  storage:
    path: backups/
    type: local
deployment:
  container:
    image: resume-system:latest
    port: 8000
  environment: development
  health_check:
    enabled: true
    endpoint: /health
    interval: 30
    timeout: 10
  resources:
    cpu_limit: '2'
    disk_limit: 10Gi
    memory_limit: 4Gi
error_handling:
  global_error_handler: true
  notifications:
    email_alerts: false
    slack_webhook: null
    webhook_url: null
  recovery:
    auto_recovery: true
    checkpoint_interval: 100
    enable_checkpoint: true
  retry_strategy:
    backoff_factor: 2
    max_attempts: 3
    max_delay: 60
external_services:
  email_service:
    enabled: false
    password: ${EMAIL_PASSWORD}
    smtp_port: 587
    smtp_server: smtp.gmail.com
    username: ${EMAIL_USERNAME}
  llm_service:
    api_key: 0175134f27a040709d7541e14b4db353.V3KP9u8rZ0oQj9s9
    model: glm-4
    provider: zhipu
    timeout: 30
  notification_service:
    enabled: false
    webhook_url: ${WEBHOOK_URL}
integration_system:
  auto_submission:
    browser_config:
      headless: false
      timeout: 30
      user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
      window_size:
      - 1920
      - 1080
    dry_run_mode: false
    enable_smart_delay: true
    max_concurrent_submissions: 3
    max_retries: 3
    max_submissions_per_day: 50
    retry_delay: 10
    submission_delay: 5
  data_bridge:
    cache_ttl: 3600
    data_retention_days: 30
    max_cache_size: 1000
    transformation_cache: true
    validation_enabled: true
  decision_engine:
    criteria:
      blacklisted_companies:
      - 黑名单公司1
      - 黑名单公司2
      min_salary_requirement: 15000
      preferred_locations:
      - 北京
      - 上海
      - 深圳
      - 杭州
      required_skills:
      - Python
      - 机器学习
      - 数据分析
    enable_learning: true
    max_daily_submissions: 50
    max_submissions_per_company: 3
    priority_threshold: 0.8
    submission_threshold: 0.7  # 适度提高投递阈值从0.7到0.72，平衡匹配数量和质量
    urgent_threshold: 0.9
    weights:
      application_competition: 0.1
      career_growth_potential: 0.1
      company_reputation: 0.2
      location_preference: 0.1
      match_score: 0.3
      salary_attractiveness: 0.2
    
    # 新增：薪资阈值过滤配置
    salary_filters:
      enabled: true                    # 启用薪资过滤
      min_salary_match_score: 0.3      # 最低薪资匹配度阈值
      strict_mode: true                # 严格模式：低于阈值直接拒绝
      fallback_strategy: "reject"      # 备选策略：reject/lower_priority
      
      # 分级阈值策略（可选）
      tiered_thresholds:
        enabled: false
        senior_positions:
          min_score: 0.5
          keywords: ["高级", "资深", "专家", "架构师", "总监"]
        regular_positions:
          min_score: 0.3
          keywords: ["工程师", "开发", "分析师"]
        entry_level:
          min_score: 0.2
          keywords: ["初级", "助理", "实习"]
    
    # 增强的薪资评估配置
    salary_enhancement:
      enabled: true
      thresholds:
        excellent: 0.8    # 薪资匹配优秀
        good: 0.6         # 薪资匹配良好
        acceptable: 0.3   # 薪资匹配可接受（最低投递线）
        poor: 0.0         # 薪资匹配较差
      
      # 薪资权重动态调整
      dynamic_weight:
        enabled: false              # 暂时禁用，保持现有权重
        base_weight: 0.2
        boost_factor: 1.5
        penalty_factor: 0.5
  job_scheduler:
    batch_size: 50
    max_concurrent_tasks: 10
    priority_levels: 5
    queue_size: 1000
    task_timeout: 300
    worker_pool_size: 5
  master_controller:
    checkpoint_interval: 100
    enable_monitoring: true
    error_retry_attempts: 3
    execution_timeout: 3600
    max_concurrent_jobs: 10
integration_tests:
  e2e_tests:
    enabled: true
    test_data_path: testdata/
  performance_tests:
    concurrent_users: 10
    enabled: true
    load_test_duration: 300
  regression_tests:
    baseline_metrics_path: tests/baseline/
    enabled: true
license:
  owner: Resume System Team
  type: MIT
  year: 2025
login:
  check_interval: 2
  failure_indicators:
  - .error-msg
  - .login-failed
  - .captcha-error
  - .password-error
  - .alert-danger
  login_url: https://www.51job.com/
  session_timeout: 7200
  success_indicators:
  - .name-span
  - 'a[href*="/pc/my/myjob"]'
  - 'a[href*="we.51job.com/pc/my"]'
  - .img-wrap
  - .uname.e_icon.at
  - .uname
  - 'a[one-link-mark="yes"].uname'
  - .user-info
  - .user-name
  - '[data-user]'
  - .logout
  - .member-center
  - .welcome-user
  wait_timeout: 300
login_mode:
  auto_save_session: true
  detail_page_delay: 3.0
  enabled: true
  login_retry_delay: 10
  max_login_attempts: 3
  require_login_for_details: true
  session_validation_interval: 300
  website: qiancheng
mode:
  close_on_complete: true
  debug: false
  development: false
  login_mode_enabled: true
  session_file: data/qiancheng_session.json
  skip_login: false
  use_saved_session: true
modules:
  job_extraction:
    concurrent_extractions: 5
    enabled: true
    extraction_timeout: 300
    max_pages_per_site: 10
    sources:
    - base_url: https://www.zhaopin.com
      enabled: true
      max_pages: 5
      name: 智联招聘
    - base_url: https://www.51job.com
      enabled: true
      max_pages: 2
      name: 前程无忧
    - base_url: https://www.zhipin.com
      enabled: true
      max_pages: 3
      name: Boss直聘
  rag_processing:
    batch_size: 50
    enabled: true
    llm_timeout: 30
    max_retries: 3
    vector_db:
      collection_name: job_positions
      embedding_dimension: 768
      similarity_threshold: 0.7
  resume_matching:
    algorithms:
    - enabled: true
      name: semantic_matching
      weight: 0.4
    - enabled: true
      name: keyword_matching
      weight: 0.2
    - enabled: true
      name: skill_matching
      weight: 0.4
    enable_semantic_matching: true
    enabled: true
    matching_threshold: 0.60  # 适度提高匹配阈值从0.6到0.68，平衡匹配数量和质量
    max_matches_per_resume: 50
monitoring:
  alert_thresholds:
    cpu_usage: 0.8
    error_rate: 0.1
    memory_usage: 0.8
    processing_speed: 100
    queue_size: 500
  logging:
    file_rotation: daily
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    level: INFO
    log_files:
      error: logs/error.log
      main: logs/integration.log
      performance: logs/performance.log
    max_file_size: 100MB
    retention_days: 30
  metrics_collection: true
  real_time_dashboard: true
performance:
  caching:
    cache_size: 10000
    enabled: true
    redis:
      db: 0
      enabled: false
      host: localhost
      password: null
      port: 6379
    ttl_seconds: 3600
  concurrency:
    max_workers: 10
    semaphore_limit: 5
    thread_pool_size: 20
  database:
    batch_insert_size: 1000
    connection_pool_size: 20
    enable_query_cache: true
    query_timeout: 30
rag_system:
  database:
    path: ./data/jobs.db
  llm:
    api_key: 0175134f27a040709d7541e14b4db353.V3KP9u8rZ0oQj9s9
    max_tokens: 1500
    model: glm-4-flash
    provider: zhipu
    temperature: 0.1
  processing:
    batch_size: 50
    chunk_overlap: 50
    chunk_size: 500
  vector_db:
    collection_name: job_positions
    persist_directory: ./data/test_chroma_db
    
    # 时间感知向量搜索配置
    time_aware_search:
      enable_time_boost: true           # 启用时间感知功能
      fresh_data_boost: 0.2             # 新数据额外加分 (0.0-0.5)
      fresh_data_days: 7                # 多少天内算作新数据
      time_decay_factor: 0.1            # 老数据时间衰减因子 (0.0-0.3)
      enable_recency_filter: false      # 是否启用时间过滤
      recency_filter_days: 30           # 时间过滤天数
      
      # 时间权重计算配置
      time_weight_config:
        fresh_weight_range: [0.7, 1.0]   # 新数据权重范围 (0-7天)
        medium_weight_range: [0.4, 0.7]  # 中等数据权重范围 (7-30天)
        old_data_min_weight: 0.1         # 老数据最小权重 (30天以上)
        exponential_decay_rate: 0.5      # 指数衰减参数
search:
  base_url: https://we.51job.com/pc/search
  current_keyword: python
  job_area: '020000'
  keyword_type: ''
  keywords:
    priority_1:
    - Python开发
    - Python工程师
    - 后端开发
    priority_2:
    - 数据分析师
    - 机器学习
    - 算法工程师
    priority_3:
    - 全栈开发
    - 软件工程师
    - 技术专家
  search_type: '2'
security:
  access_control:
    api_key_required: false
    enable_auth: false
  encryption:
    algorithm: AES-256
    enabled: false
  privacy:
    anonymize_logs: true
    data_retention_days: 90
selectors:
  job_detail:
    apply_button: .apply-btn
    benefits: .job-benefits
    company_info: .company-info
    job_description: .job-description
    requirements: .job-requirements
  search_page:
    company_name: .cname
    job_list: .joblist
    job_title: .jname a
    location: .area
    next_page: .btn-next
    salary: .sal
testing:
  mock_data:
    enabled: false
    job_count: 100
  test_database:
    auto_cleanup: true
    use_separate_db: true
  test_mode: false
# 简历处理系统配置
resume_processing:
  # 文档解析配置
  document_parser:
    supported_formats: ['md', 'docx', 'pdf', 'txt']
    max_file_size_mb: 10
    encoding: 'utf-8'
    
  # RAG处理配置
  rag_processor:
    llm_provider: 'zhipu'
    model: 'glm-4-flash'
    temperature: 0.1
    max_tokens: 4000
    retry_attempts: 3
    timeout_seconds: 60
    
  # 数据验证配置
  validation:
    required_fields: ['name', 'total_experience_years']
    min_work_history_entries: 1
    max_skills_per_category: 20
    
  # 质量控制配置
  quality_control:
    min_completeness_score: 0.7
    enable_manual_review: false
    auto_fix_common_issues: true

# 简历匹配配置 - 针对20年经验资深人士优化 (已优化解决qc_167002415匹配问题)
resume_matching_advanced:
  # 搜索范围配置 - 增加搜索范围以匹配更多职位
  default_search_k: 3000      # 语义搜索返回的候选文档数量，从默认80增加到1000
  max_results: 3000           # 最大匹配结果数量
  
  # 时间感知匹配配置 - 解决新数据被老数据掩盖的问题
  time_aware_matching:
    enable_time_aware: true                # 启用时间感知匹配
    search_strategy: "hybrid"              # 搜索策略: hybrid/fresh_first/balanced
    
    # 新数据优先级配置
    fresh_data_priority:
      enable: true                         # 启用新数据优先
      boost_multiplier: 1.3               # 新数据分数倍增器
      min_similarity: 0.3                 # 新数据最低相似度要求
      
    # 时间权重混合配置
    time_weight_mixing:
      similarity_weight: 0.65              # 相似度权重 (降低为时间让路)
      time_weight: 0.35                    # 时间权重 (新增)
      
    # 搜索策略配置
    strategy_config:
      hybrid:
        similarity_ratio: 0.7              # 混合策略中相似度比例
        time_ratio: 0.3                    # 混合策略中时间比例
      fresh_first:
        fresh_boost: 0.25                  # 新数据优先策略加分
        old_penalty: 0.15                  # 老数据惩罚
      balanced:
        equal_weight: 0.5                  # 平衡策略权重
  
  # 优化后的权重配置 - 进一步提高薪资权重过滤低薪职位
  matching_weights:
    semantic_similarity: 0.25  # 语义相似度（适当降低，为薪资让出权重）
    skills_match: 0.40         # 技能匹配（降低权重，避免过度匹配）
    experience_match: 0.10     # 经验匹配（保持权重，重视资深经验）
    industry_match: 0.05       # 行业匹配（保持权重，重视行业经验）
    salary_match: 0.20         # 薪资匹配（大幅提高权重，强力过滤低薪职位）
  
  # 优化后的匹配质量等级阈值配置 - 平衡匹配数量和质量
  match_thresholds:
    excellent: 0.75    # 优秀匹配：75分以上（强烈推荐申请）
    good: 0.65         # 良好匹配：65-74分（推荐申请）
    fair: 0.55         # 一般匹配：55-64分（可以考虑）
    poor: 0.45         # 最低匹配：45分以上（适中阈值，平衡数量和质量）
  
  # 技能权重配置
  skill_weights:
    # 编程语言
    python: 1.6
    java: 1.5
    javascript: 1.4
    typescript: 1.4
    go: 1.3
    rust: 1.3
    
    # 前端技术
    react: 1.3
    vue: 1.3
    angular: 1.3
    
    # 后端框架
    spring: 1.3
    django: 1.3
    flask: 1.2
    express: 1.2
    
    # 数据库
    mysql: 1.3
    postgresql: 1.3
    mongodb: 1.2
    redis: 1.2
    elasticsearch: 1.2
    
    # 云平台和容器
    docker: 1.4
    kubernetes: 1.5
    aws: 1.5
    azure: 1.5
    gcp: 1.4
    
    # AI/ML
    machine_learning: 1.7
    deep_learning: 1.6
    ai: 1.8
    tensorflow: 1.6
    pytorch: 1.6
    scikit_learn: 1.4
    
    # 大数据
    spark: 1.4
    hadoop: 1.3
    kafka: 1.3
    
    # 开发工具
    git: 1.2
    linux: 1.3
    devops: 1.4
    ci_cd: 1.3
  
  # 分类权重倍数
  category_multipliers:
    core_skills: 1.0
    programming_languages: 0.9
    cloud_platforms: 0.8
    ai_ml_skills: 1.1
    data_engineering_skills: 0.9
    management_skills: 0.7
  
  # 熟练程度权重倍数
  proficiency_multipliers:
    expert: 1.2
    advanced: 1.0
    intermediate: 0.8
    beginner: 0.6
  
  # 增强职位标题映射 - 解决语义匹配问题
  position_mappings:
    "后端开发工程师":
      - "数据平台架构师"
      - "系统架构师"
      - "技术架构师"
      - "高级开发工程师"
      - "技术专家"
      - "技术负责人"
    
    "数据工程师":
      - "后端开发工程师"
      - "系统开发工程师"
      - "平台开发工程师"
  
  # 增强技能映射和权重
  enhanced_skill_mappings:
    # 后端开发相关技能映射
    backend_development:
      core_skills:
        - "Python"
        - "Java"
        - "数据库设计"
        - "系统架构"
        - "API设计"
      
      # 将数据工程技能映射到后端开发
      data_to_backend:
        "数据平台架构": ["后端架构设计", "系统设计", "平台开发"]
        "数据工程": ["后端开发", "数据处理", "ETL开发"]
        "Databricks": ["大数据处理", "分布式系统", "后端服务"]
        "Azure": ["云平台开发", "后端服务部署"]
        "数据治理": ["数据管理", "后端数据服务"]
    
    # 架构师技能加分
    architect_bonus:
      "系统架构设计": 1.5
      "技术架构": 1.5
      "平台架构": 1.4
      "数据架构": 1.3
      "分布式系统": 1.4
      "微服务": 1.3
  
  # 经验层次加分规则
  experience_bonus:
    senior_architect:  # 15年以上架构师
      min_years: 15
      position_keywords: ["架构师", "技术专家", "技术负责人"]
      bonus_multiplier: 1.3
      
    expert_level:  # 20年以上专家
      min_years: 20
      bonus_multiplier: 1.5
  
  # 行业经验加分
  industry_bonus:
    pharmaceutical: 1.2  # 制药行业经验加分
    healthcare: 1.1      # 医疗行业经验加分
    
  # 语义相似度优化
  semantic_optimization:
    # 职位描述关键词扩展
    job_title_expansion:
      "后端开发工程师":
        - "系统开发"
        - "平台开发"
        - "架构设计"
        - "技术实现"
        - "数据处理"
        - "服务开发"
    
    # 技能上下文理解
    skill_context:
      python_contexts:
        - "数据处理"
        - "后端开发"
        - "系统开发"
        - "API开发"
        - "自动化"
      
      database_contexts:
        - "数据库设计"
        - "数据建模"
        - "后端存储"
        - "数据架构"
    
    # 降低纯文本匹配要求，增加技能和经验权重
    text_similarity_threshold: 0.1  # 降低文本相似度要求
    skill_similarity_boost: 2.0     # 技能匹配加倍
    experience_similarity_boost: 1.5 # 经验匹配加成

# 批量处理配置
batch_processing:
  # 并发控制
  max_concurrent_files: 3
  rate_limit_delay: 1  # 秒
  
  # 错误处理
  max_retry_per_file: 2
  continue_on_error: true
  
  # 输出配置
  create_summary_report: true
  save_failed_files_list: true

version:
  config_version: 1.0.0
  last_updated: '2025-08-27'
  system_version: 1.0.0
