backup:
  auto_backup: true
  backup_interval: daily
  retention:
    daily_backups: 7
    monthly_backups: 12
    weekly_backups: 4
  storage:
    path: backups/
    type: local
deployment:
  container:
    image: resume-system:latest
    port: 8000
  environment: development
  health_check:
    enabled: true
    endpoint: /health
    interval: 30
    timeout: 10
  resources:
    cpu_limit: '2'
    disk_limit: 10Gi
    memory_limit: 4Gi
error_handling:
  global_error_handler: true
  notifications:
    email_alerts: false
    slack_webhook: null
    webhook_url: null
  recovery:
    auto_recovery: true
    checkpoint_interval: 100
    enable_checkpoint: true
  retry_strategy:
    backoff_factor: 2
    max_attempts: 3
    max_delay: 60
external_services:
  email_service:
    enabled: false
    password: ${EMAIL_PASSWORD}
    smtp_port: 587
    smtp_server: smtp.gmail.com
    username: ${EMAIL_USERNAME}
  llm_service:
    api_key: 0175134f27a040709d7541e14b4db353.V3KP9u8rZ0oQj9s9
    model: glm-4
    provider: zhipu
    timeout: 30
  notification_service:
    enabled: false
    webhook_url: ${WEBHOOK_URL}
integration_system:
  auto_submission:
    browser_config:
      headless: false
      timeout: 30
      user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
      window_size:
      - 1920
      - 1080
    dry_run_mode: false
    enable_smart_delay: true
    max_concurrent_submissions: 3
    max_retries: 3
    max_submissions_per_day: 50
    retry_delay: 10
    submission_delay: 5
  data_bridge:
    cache_ttl: 3600
    data_retention_days: 30
    max_cache_size: 1000
    transformation_cache: true
    validation_enabled: true
  decision_engine:
    criteria:
      blacklisted_companies:
      - 黑名单公司1
      - 黑名单公司2
      min_salary_requirement: 15000
      preferred_locations:
      - 北京
      - 上海
      - 深圳
      - 杭州
      required_skills:
      - Python
      - 机器学习
      - 数据分析
    enable_learning: true
    max_daily_submissions: 50
    max_submissions_per_company: 3
    priority_threshold: 0.8
    submission_threshold: 0.7
    urgent_threshold: 0.9
    weights:
      application_competition: 0.1
      career_growth_potential: 0.1
      company_reputation: 0.2
      location_preference: 0.1
      match_score: 0.3
      salary_attractiveness: 0.2
  job_scheduler:
    batch_size: 50
    max_concurrent_tasks: 10
    priority_levels: 5
    queue_size: 1000
    task_timeout: 300
    worker_pool_size: 5
  master_controller:
    checkpoint_interval: 100
    enable_monitoring: true
    error_retry_attempts: 3
    execution_timeout: 3600
    max_concurrent_jobs: 10
integration_tests:
  e2e_tests:
    enabled: true
    test_data_path: testdata/
  performance_tests:
    concurrent_users: 10
    enabled: true
    load_test_duration: 300
  regression_tests:
    baseline_metrics_path: tests/baseline/
    enabled: true
license:
  owner: Resume System Team
  type: MIT
  year: 2025
login:
  check_interval: 2
  failure_indicators:
  - .error-msg
  - .login-failed
  - .captcha-error
  - .password-error
  - .alert-danger
  login_url: https://www.51job.com/
  session_timeout: 7200
  success_indicators:
  - .name-span
  - 'a[href*="/pc/my/myjob"]'
  - 'a[href*="we.51job.com/pc/my"]'
  - .img-wrap
  - .uname.e_icon.at
  - .uname
  - 'a[one-link-mark="yes"].uname'
  - .user-info
  - .user-name
  - '[data-user]'
  - .logout
  - .member-center
  - .welcome-user
  wait_timeout: 300
login_mode:
  auto_save_session: true
  detail_page_delay: 3.0
  enabled: true
  login_retry_delay: 10
  max_login_attempts: 3
  require_login_for_details: true
  session_validation_interval: 300
  website: qiancheng
mode:
  close_on_complete: true
  debug: false
  development: false
  login_mode_enabled: true
  session_file: data/qiancheng_session.json
  skip_login: false
  use_saved_session: true
modules:
  job_extraction:
    concurrent_extractions: 5
    enabled: true
    extraction_timeout: 300
    max_pages_per_site: 10
    sources:
    - base_url: https://www.zhaopin.com
      enabled: true
      max_pages: 5
      name: 智联招聘
    - base_url: https://www.51job.com
      enabled: true
      max_pages: 2
      name: 前程无忧
    - base_url: https://www.zhipin.com
      enabled: true
      max_pages: 3
      name: Boss直聘
  rag_processing:
    batch_size: 50
    enabled: true
    llm_timeout: 30
    max_retries: 3
    vector_db:
      collection_name: job_positions
      embedding_dimension: 768
      similarity_threshold: 0.7
  resume_matching:
    algorithms:
    - enabled: true
      name: semantic_matching
      weight: 0.4
    - enabled: true
      name: keyword_matching
      weight: 0.2
    - enabled: true
      name: skill_matching
      weight: 0.4
    enable_semantic_matching: true
    enabled: true
    matching_threshold: 0.6
    max_matches_per_resume: 50
monitoring:
  alert_thresholds:
    cpu_usage: 0.8
    error_rate: 0.1
    memory_usage: 0.8
    processing_speed: 100
    queue_size: 500
  logging:
    file_rotation: daily
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    level: INFO
    log_files:
      error: logs/error.log
      main: logs/integration.log
      performance: logs/performance.log
    max_file_size: 100MB
    retention_days: 30
  metrics_collection: true
  real_time_dashboard: true
performance:
  caching:
    cache_size: 10000
    enabled: true
    redis:
      db: 0
      enabled: false
      host: localhost
      password: null
      port: 6379
    ttl_seconds: 3600
  concurrency:
    max_workers: 10
    semaphore_limit: 5
    thread_pool_size: 20
  database:
    batch_insert_size: 1000
    connection_pool_size: 20
    enable_query_cache: true
    query_timeout: 30
rag_system:
  database:
    path: ./data/jobs.db
  llm:
    api_key: 0175134f27a040709d7541e14b4db353.V3KP9u8rZ0oQj9s9
    max_tokens: 1500
    model: glm-4-flash
    provider: zhipu
    temperature: 0.1
  processing:
    batch_size: 50
    chunk_overlap: 50
    chunk_size: 500
  vector_db:
    collection_name: job_positions
    persist_directory: ./data/test_chroma_db
search:
  base_url: https://we.51job.com/pc/search
  current_keyword: python
  job_area: '020000'
  keyword_type: ''
  keywords:
    priority_1:
    - Python开发
    - Python工程师
    - 后端开发
    priority_2:
    - 数据分析师
    - 机器学习
    - 算法工程师
    priority_3:
    - 全栈开发
    - 软件工程师
    - 技术专家
  search_type: '2'
security:
  access_control:
    api_key_required: false
    enable_auth: false
  encryption:
    algorithm: AES-256
    enabled: false
  privacy:
    anonymize_logs: true
    data_retention_days: 90
selectors:
  job_detail:
    apply_button: .apply-btn
    benefits: .job-benefits
    company_info: .company-info
    job_description: .job-description
    requirements: .job-requirements
  search_page:
    company_name: .cname
    job_list: .joblist
    job_title: .jname a
    location: .area
    next_page: .btn-next
    salary: .sal
testing:
  mock_data:
    enabled: false
    job_count: 100
  test_database:
    auto_cleanup: true
    use_separate_db: true
  test_mode: false
version:
  config_version: 1.0.0
  last_updated: '2025-08-22'
  system_version: 1.0.0
