# 简历职位匹配系统配置文件
# 基于设计文档的占彬专用配置

resume_matching:
  # 匹配权重配置
  weights:
    semantic_similarity: 0.35  # 语义相似度权重
    skills_match: 0.30         # 技能匹配权重（重要）
    experience_match: 0.20     # 经验匹配权重
    industry_match: 0.10       # 行业匹配权重
    salary_match: 0.05         # 薪资匹配权重

  # 占彬的技能权重配置
  skills_weights:
    # 最新学习技能（最高权重）
    RAG: 2.0
    rag: 2.0
    
    # AI/ML发展方向
    AI/ML: 1.9
    "ai/ml": 1.9
    "machine learning": 1.9
    "机器学习": 1.9
    "artificial intelligence": 1.9
    "人工智能": 1.9
    
    # 认证专家技能
    Azure: 1.8
    azure: 1.8
    LangChain: 1.8
    langchain: 1.8
    
    # 核心专业技能
    Databricks: 1.7
    databricks: 1.7
    "数据架构": 1.7
    "data architecture": 1.7
    
    # 主要编程语言和框架
    Python: 1.6
    python: 1.6
    PyTorch: 1.6
    pytorch: 1.6
    TensorFlow: 1.6
    tensorflow: 1.6
    
    # 管理和方法论
    "技术管理": 1.5
    "technical management": 1.5
    "team leadership": 1.5
    "项目管理": 1.4
    "project management": 1.4
    Scrum: 1.3
    scrum: 1.3
    "敏捷开发": 1.3
    
    # 数据工程技能
    "数据建模": 1.4
    "data modeling": 1.4
    ETL: 1.3
    etl: 1.3
    "数据仓库": 1.4
    "data warehouse": 1.4
    "大数据": 1.4
    "big data": 1.4
    
    # 云和容器技术
    "云架构": 1.5
    "cloud architecture": 1.5
    AWS: 1.4
    aws: 1.4
    Docker: 1.3
    docker: 1.3
    Kubernetes: 1.3
    kubernetes: 1.3
    
    # 数据库技能
    SQL: 1.3
    sql: 1.3
    "数据库": 1.3
    database: 1.3
    
    # 其他相关技能
    "深度学习": 1.6
    "deep learning": 1.6
    "自然语言处理": 1.5
    NLP: 1.5
    nlp: 1.5
    "计算机视觉": 1.4
    "computer vision": 1.4

  # 匹配阈值配置
  thresholds:
    excellent: 0.85    # 优秀匹配阈值
    good: 0.70         # 良好匹配阈值
    fair: 0.50         # 一般匹配阈值
    poor: 0.30         # 较差匹配阈值

  # 搜索和匹配参数
  search:
    default_search_k: 60        # 默认搜索候选数量
    min_score_threshold: 0.3    # 最低分数阈值
    max_results: 20             # 最大返回结果数
    
  # 性能优化配置
  performance:
    batch_size: 50              # 批处理大小
    max_candidates: 100         # 最大候选职位数
    cache_ttl: 3600            # 缓存生存时间（秒）
    timeout: 30                # 处理超时时间（秒）
    enable_parallel: true       # 启用并行处理
    max_workers: 4             # 最大工作线程数

  # 向量化配置
  vectorization:
    document_weights:
      skills_overview: 1.0      # 技能概览文档权重
      experience_overview: 0.9  # 经验概览文档权重
      industry_background: 0.8  # 行业背景文档权重
      career_objectives: 0.7    # 职业目标文档权重
      work_experience: 0.8      # 单个工作经历权重

  # 技能同义词映射
  skill_synonyms:
    "machine learning":
      - "机器学习"
      - "ML"
      - "ml"
    "artificial intelligence":
      - "人工智能"
      - "AI"
      - "ai"
    "deep learning":
      - "深度学习"
      - "DL"
      - "dl"
    "natural language processing":
      - "自然语言处理"
      - "NLP"
      - "nlp"
    "computer vision":
      - "计算机视觉"
      - "CV"
      - "cv"
    "data science":
      - "数据科学"
      - "数据分析"
    "data engineering":
      - "数据工程"
      - "数据开发"
    "cloud computing":
      - "云计算"
      - "云服务"
    "containerization":
      - "容器化"
      - "容器技术"

  # 行业相关性配置
  industry_relations:
    "科技":
      - "互联网"
      - "AI"
      - "软件"
      - "技术"
      - "IT"
    "制药":
      - "医疗"
      - "生物"
      - "健康"
      - "生命科学"
    "金融":
      - "银行"
      - "保险"
      - "投资"
      - "证券"
    "咨询":
      - "管理"
      - "战略"
      - "顾问"
      - "服务"

  # 薪资分析配置
  salary_analysis:
    currency: "CNY"             # 货币单位
    annual_basis: true          # 年薪制
    market_adjustment: 1.0      # 市场调整系数
    
  # 报告生成配置
  reporting:
    include_detailed_analysis: true    # 包含详细分析
    include_recommendations: true      # 包含推荐建议
    include_skill_gaps: true          # 包含技能差距分析
    include_salary_analysis: true     # 包含薪资分析
    max_recommendations: 10           # 最大推荐数量

# 日志配置
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/resume_matching.log"
  max_size: "10MB"
  backup_count: 5

# 缓存配置
cache:
  enabled: true
  type: "memory"              # 缓存类型：memory, redis
  max_size: 1000             # 最大缓存条目数
  ttl: 3600                  # 生存时间（秒）

# 监控配置
monitoring:
  enabled: true
  metrics_collection: true
  performance_tracking: true
  error_tracking: true
  
# 测试配置
testing:
  mock_data_enabled: false
  test_job_count: 100
  benchmark_enabled: true