# 简历处理系统配置文件

resume_processing:
  # 文档解析配置
  document_parser:
    supported_formats: ['md', 'docx', 'pdf', 'txt']
    max_file_size_mb: 10
    encoding: 'utf-8'
    
  # RAG处理配置  
  rag_processor:
    llm_provider: 'zhipu'
    model: 'glm-4-flash'
    temperature: 0.1
    max_tokens: 4000
    retry_attempts: 3
    timeout_seconds: 60
    
  # 数据验证配置
  validation:
    required_fields: ['name', 'total_experience_years']
    min_work_history_entries: 1
    max_skills_per_category: 20
    
  # 质量控制配置
  quality_control:
    min_completeness_score: 0.7
    enable_manual_review: false
    auto_fix_common_issues: true

# 简历匹配配置
resume_matching:
  # 匹配权重配置
  matching_weights:
    semantic_similarity: 0.35  # 语义相似度
    skills_match: 0.30         # 技能匹配（重要）
    experience_match: 0.20     # 经验匹配
    industry_match: 0.10       # 行业匹配
    salary_match: 0.05         # 薪资匹配
  
  # 匹配阈值配置
  match_thresholds:
    excellent: 0.85
    good: 0.70
    fair: 0.50
    poor: 0.30
  
  # 技能权重配置
  skill_weights:
    # 编程语言
    python: 1.6
    java: 1.5
    javascript: 1.4
    typescript: 1.4
    go: 1.3
    rust: 1.3
    
    # 前端技术
    react: 1.3
    vue: 1.3
    angular: 1.3
    
    # 后端框架
    spring: 1.3
    django: 1.3
    flask: 1.2
    express: 1.2
    
    # 数据库
    mysql: 1.3
    postgresql: 1.3
    mongodb: 1.2
    redis: 1.2
    elasticsearch: 1.2
    
    # 云平台和容器
    docker: 1.4
    kubernetes: 1.5
    aws: 1.5
    azure: 1.5
    gcp: 1.4
    
    # AI/ML
    machine learning: 1.7
    deep learning: 1.6
    ai: 1.8
    tensorflow: 1.6
    pytorch: 1.6
    scikit-learn: 1.4
    
    # 大数据
    spark: 1.4
    hadoop: 1.3
    kafka: 1.3
    
    # 开发工具
    git: 1.2
    linux: 1.3
    devops: 1.4
    ci/cd: 1.3
  
  # 分类权重倍数
  category_multipliers:
    core_skills: 1.0
    programming_languages: 0.9
    cloud_platforms: 0.8
    ai_ml_skills: 1.1
    data_engineering_skills: 0.9
    management_skills: 0.7
  
  # 熟练程度权重倍数
  proficiency_multipliers:
    expert: 1.2
    advanced: 1.0
    intermediate: 0.8
    beginner: 0.6

# 批量处理配置
batch_processing:
  # 并发控制
  max_concurrent_files: 3
  rate_limit_delay: 1  # 秒
  
  # 错误处理
  max_retry_per_file: 2
  continue_on_error: true
  
  # 输出配置
  create_summary_report: true
  save_failed_files_list: true

# 日志配置
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s'
  
  # 文件日志
  file_logging:
    enabled: true
    log_file: './logs/resume_processing.log'
    max_size_mb: 10
    backup_count: 5
  
  # 关键日志点
  log_points:
    document_parsing: true
    rag_extraction: true
    data_validation: true
    profile_creation: true

# 性能配置
performance:
  # 缓存配置
  enable_content_cache: true
  cache_ttl_hours: 24
  
  # 内存管理
  max_memory_per_file_mb: 100
  gc_after_files: 10
  
  # 超时配置
  document_parse_timeout: 30
  rag_processing_timeout: 120
  total_processing_timeout: 300

# 测试配置
testing:
  # 测试数据
  sample_resumes_dir: './test_data/sample_resumes'
  expected_outputs_dir: './test_data/expected_outputs'
  
  # 测试参数
  test_formats: ['md', 'docx', 'pdf']
  test_batch_sizes: [1, 3, 5]
  
  # 质量基准
  min_extraction_accuracy: 0.85
  max_processing_time_per_file: 60