# 投递简历功能配置文件

submission_engine:
  # 基础配置
  batch_size: 10                    # 批次大小
  max_daily_submissions: 50         # 每日最大投递数量
  submission_delay_range: [3.0, 8.0]  # 投递延迟范围（秒）
  max_retries: 3                    # 最大重试次数
  retry_delay: 10                   # 重试延迟（秒）
  skip_on_error: true               # 遇到错误是否跳过

  # 登录配置
  auto_login_enabled: true          # 是否启用自动登录
  manual_login_timeout: 300         # 手动登录超时时间（秒）
  session_check_interval: 60       # 会话检查间隔（秒）

  # 反爬虫配置
  random_delay: true                # 是否启用随机延迟
  user_agent_rotation: true        # 是否轮换User-Agent
  mouse_simulation: true            # 是否启用鼠标模拟
  scroll_simulation: true           # 是否启用滚动模拟

  # 按钮识别配置
  button_timeout: 10                # 按钮查找超时时间（秒）
  button_retry_attempts: 3          # 按钮点击重试次数

# 按钮识别选择器配置
button_recognition:
  timeout: 10
  retry_attempts: 3
  selectors:
    qiancheng:  # 51job
      - "a.but_sq#app_ck"
      - "a[onclick*='delivery']"
      - "a[track-type='NewTrackButtonClick']"
      - "button:contains('申请职位')"
      - "a:contains('申请职位')"
      - ".apply-btn"
      - "#apply-button"
    
    zhilian:  # 智联招聘
      - "button.apply-btn"
      - "a.apply-position"
      - "button:contains('立即申请')"
      - "a:contains('立即申请')"
      - ".btn-apply"
    
    boss:  # Boss直聘
      - "button.btn-apply"
      - "a.start-chat-btn"
      - "button:contains('立即沟通')"
      - "a:contains('立即沟通')"
      - ".chat-btn"
    
    lagou:  # 拉勾网
      - "a.position-apply-btn"
      - "button:contains('申请')"
      - ".apply-btn"
    
    generic:  # 通用选择器
      - "button:contains('申请')"
      - "button:contains('投递')"
      - "button:contains('立即申请')"
      - "a:contains('申请职位')"
      - "a:contains('投递简历')"
      - ".apply-btn"
      - ".submit-btn"
      - "#apply"
      - "#submit"

# 反爬虫详细配置
anti_crawler:
  random_delay: true
  user_agent_rotation: true
  mouse_simulation: true
  scroll_simulation: true
  
  # 请求头配置
  request_headers:
    Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
    Accept-Language: "zh-CN,zh;q=0.8,en-US;q=0.5,en;q=0.3"
    Accept-Encoding: "gzip, deflate, br"
    Connection: "keep-alive"
    Upgrade-Insecure-Requests: "1"
    Sec-Fetch-Dest: "document"
    Sec-Fetch-Mode: "navigate"
    Sec-Fetch-Site: "none"
    Cache-Control: "max-age=0"

  # User-Agent池（可选，使用默认的如果为空）
  user_agents: []

# 行为模拟配置（复用现有的behavior_simulator配置）
anti_bot:
  random_delay: true
  mouse_simulation: true
  scroll_simulation: true
  mouse_speed: "normal"      # slow, normal, fast
  scroll_speed: "normal"
  typing_speed: "normal"

# 错误处理配置
error_handling:
  max_retries: 3
  retry_delay: 10
  skip_on_error: true
  log_errors: true
  
  # 错误类型处理策略
  strategies:
    login_required:
      action: "retry"         # retry, skip, abort
      max_attempts: 2
    
    button_not_found:
      action: "skip"
      log_level: "warning"
    
    network_error:
      action: "retry"
      max_attempts: 3
      delay: 30
    
    page_load_timeout:
      action: "retry"
      max_attempts: 2
      delay: 15

# 监控和日志配置
monitoring:
  enable_detailed_logging: true
  log_level: "INFO"          # DEBUG, INFO, WARNING, ERROR
  
  # 统计信息收集
  collect_stats: true
  stats_interval: 100        # 每处理多少个职位输出一次统计
  
  # 性能监控
  performance_monitoring: true
  slow_operation_threshold: 30  # 超过30秒的操作记录为慢操作

# 安全配置
security:
  # 每日限制
  daily_limits:
    max_submissions: 50
    reset_time: "00:00"      # 每日重置时间
  
  # 批次限制
  batch_limits:
    max_batch_size: 20
    batch_interval: 120      # 批次间隔（秒）
  
  # 风险控制
  risk_control:
    enable_risk_assessment: true
    high_risk_delay: [300, 600]    # 高风险延迟范围（秒）
    medium_risk_delay: [60, 180]   # 中等风险延迟范围（秒）

# 数据库配置
database:
  # 投递日志保留天数
  log_retention_days: 30
  
  # 自动清理配置
  auto_cleanup: true
  cleanup_interval: 7        # 每7天清理一次

# 测试配置
testing:
  dry_run_mode: false        # 干运行模式，不实际投递
  test_urls: []              # 测试用的职位URL列表
  mock_success_rate: 0.8     # 模拟成功率（干运行模式下使用）

# 集成配置
integration:
  # 与主控制器的集成
  enable_master_controller_integration: true
  
  # 报告生成
  generate_reports: true
  report_format: "json"      # json, csv, html
  report_path: "reports/submissions/"
  
  # 通知配置
  notifications:
    enable_email_notifications: false
    email_recipients: []
    
    enable_webhook_notifications: false
    webhook_url: ""
    
    # 通知触发条件
    triggers:
      batch_complete: true
      daily_limit_reached: true
      high_error_rate: true   # 错误率超过50%时通知

# 版本信息
version:
  config_version: "1.0.0"
  last_updated: "2025-08-25"
  compatible_engine_versions: ["1.0.0"]